name: CI

on:
  push:
  pull_request:
  # Also allow running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Run the type checker and then run the tests
        run: |
          echo "lol"

  lingua-franca:
    runs-on: ubuntu-latest
    steps:
      - name: one
        run: |
          echo "${{ github.event_name }}"
          echo "${{ github.event.pull_request.head }}"
          echo "${{ github.event.pull_request.base }}"
      - name: Perform Lingua Franca TypeScript tests
        run: |
          echo "${{ github.repositoryUrl }}#${{ github.head_ref || github.ref_name }}"
