name: CI

on:
  push:
  pull_request:
  # Also allow running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out reactor-ts repository
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run the type checker and then run the tests
        run: |
          npm install
          npm run build
          npm run test

  lingua-franca:
    runs-on: ubuntu-latest
    steps:
      - name: Check out reactor-ts repository version 1
        uses: actions/checkout@v3
        with: 
          path: "reactor-ts"
          fetch-depth: 0
      - name: Read lingua-franca-ref.txt
        run: echo "lingua-franca-ref=$(cat ./reactor-ts/lingua-franca-ref.txt)" >> $GITHUB_ENV
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          repository: lf-lang/lingua-franca
          ref: ${{ env.lingua-franca-ref }}
          fetch-depth: 0
          path: "lingua-franca"
          submodules: true
      - name: Move Lingua Franca to default pwd
        run: |
          shopt -s dotglob
          mv -- ./lingua-franca/* ${{ github.workspace }}
          shopt -u dotglob 
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install RTI
        uses: ./.github/actions/install-rti
        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Perform Lingua Franca TypeScript tests
        run: |
          echo './gradlew test --tests org.lflang.tests.runtime.TypeScriptTest.* -Druntime="file://${{ github.workspace }}/reactor-ts"'
          ./gradlew --dry-run test --tests org.lflang.tests.runtime.TypeScriptTest.* -Druntime="file://${{ github.workspace }}/reactor-ts"
