name: CI

on:
  push:
  pull_request:
  # Also allow running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:          
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 10
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          #check-latest: # optional
          # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
          cache: npm
          # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: package-lock.json
      
      # Runs a single command using the runners shell
      - name: Run the tests
        run: |
          npm install
          npm run test

  # FIXME: Move reuseable workflow to lingua-franca repo
  fetch-lf:
    uses: lf-lang/reactor-ts/.github/workflows/extract-ref.yml@ci
    with:
      name: 'lingua-franca'
  
  lf-tests:
    needs: fetch-lf
    uses: lf-lang/lingua-franca/.github/workflows/ts-tests.yml@master
    with:
      runtime-ref: ${{ github.ref }}
      compiler-ref: ${{ needs.fetch-lf.outputs.ref }}
