name: CI

on:
  push:
  pull_request:
  # Also allow running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Run the type checker and then run the tests
        run: |
          echo "lol"

  lingua-franca:
    runs-on: ubuntu-latest
    steps:
      - name: Check out reactor-ts repository
        uses: actions/checkout@v3
        with: 
          path: "ts-reactor"
          fetch-depth: 0
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          repository: lf-lang/lingua-franca
          ref: ${{ env.lingua-franca-ref }}
          fetch-depth: 0
          submodules: true
          path: "lingua-franca"
      - name: haha
        run: |
          ls
          echo "${{ github.event_name }}"
          echo "${{ github.event.pull_request.head.repo.git_url }}"
      - name: Perform Lingua Franca TypeScript tests
        run: |
          echo "${{ github.repositoryUrl }}#${{ github.head_ref || github.ref_name }}"
